# -*- coding: utf-8 -*-
#
# WBM-Library documentation build configuration file, created by
# sphinx-quickstart on Wed Jan 10 11:05:36 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

# Directories to the Matlab source code of the WBM-Library:
#sys.path.insert(0, os.path.abspath('../../'))
sys.path.insert(0, os.path.abspath('../../../'))
#sys.path.insert(0, os.path.abspath('../../../utilities/+WBM/'))
#sys.path.insert(0, os.path.abspath('../../../utilities/+WBM/+utilities/'))
#print(sys.path)


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '1.7.2'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.githubpages',
              'sphinx.ext.ifconfig',
              'sphinx.ext.mathjax',
              'sphinx.ext.napoleon',
              'sphinx.ext.viewcode',
              'sphinxcontrib.bibtex',
              'sphinxcontrib.matlab']

# Render math via JavaScript:
#   extensions = ['sphinx.ext.mathjax']
#
mathjax_path = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML' # the latest release

# Render math as images:
#   extensions = ['sphinx.ext.imgmath']
#
#imgmath_image_format = 'svg'
#imgmath_latex_preamble = r'''
#\usepackage{amsmath, amsfonts, amssymb, amsthm}
#\usepackage{siunitx} % SI-units package
#'''
#imgmath_font_size = 11

# GraphViz:
#   extensions = ['sphinx.ext.graphviz']

# PlantUML:
#   extensions = ['sphinxcontrib.plantuml']
#
# Path to the executable file of PlantUML:
#plantuml = 'java -jar /usr/share/plantuml/plantuml.jar'

# Directory to the Matlab sources of the WBM-Library:
matlab_src_dir = os.path.abspath('../../')

# Set the primary language domain to Matlab.
primary_domain = 'mat'

# Napoleon settings:
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = False # (default: True)
napoleon_use_keyword = False # (default: True)

# Automatic numbering of figures, tables, code-blocks
# and sections if they have a caption.
numfig = True # (default: False)

numfig_format = {'figure': 'Fig. %s', 'table': 'Table %s',
                 'code-block': 'Listing %s', 'section': 'Section %s'}

#autodoc_default_flags = ['members', 'inherited-members']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'WBM-Library'
copyright = u'2018, Martin Neururer'
author = u'Martin Neururer'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.9'
# The full version, including alpha/beta/rc tags.
release = version + u'beta'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None # (default: None)

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
today = u'Jun 25, 2018'
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
if (os.environ.get('READTHEDOCS', None) == 'True'):
    html_theme = 'sphinxdoc'
else:
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

    html_theme_options = {
        'canonical_url': '',
        'analytics_id': '',
        'logo_only': False,
        'display_version': True,
        'prev_next_buttons_location': 'bottom',
        'style_external_links': False,
        #'vcs_pageview_mode': '',
        # Toc options:
        'collapse_navigation': True,
        'sticky_navigation': True,
        'navigation_depth': 4,
        'includehidden': True,
        'titles_only': False
    }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'WBM-Librarydoc'


# -- Options for LaTeX output ---------------------------------------------

_preamble = r'''
\usepackage{amsmath, amsfonts, amssymb, amsthm} % math packages
\usepackage{siunitx} % SI-units package

% Spacing between the lines of the document:
\usepackage{setspace}
%\onehalfspacing
%\doublespacing
\singlespacing

% Footnote back-reference link to move back
% to the place of the footnote in the text:
%\usepackage{footnotebackref}

% Control over the typography of the Table of Contents,
% List of Figures and List of Tables, etc:
%\usepackage[titles]{tocloft}
%\cftsetpnumwidth{1.25cm} % box width of the page number
%\cftsetrmarg{1.5cm}      % title texts will end before reaching the righthand margin
%\setlength{\cftchapnumwidth}{0.75cm}        % box width of the chapter number
%\setlength{\cftsecindent}{\cftchapnumwidth} % indentation length of the sections
%\setlength{\cftsecnumwidth}{1.25cm}         % box width of the section number

% tocbibind:
%   Enables the titles of the Table of Contents (ToC), the
%   List of Figures (LoF), the List of Tables (LoT), the
%   Bibliography and the Index all to be added to the Table
%   of Contents. It reduces the spaces after heading of the
%   Table of Contents, figures and tables by applying in
%   the document for example:
%       \addtocontents{toc}{\vskip -1.2cm}
%       \addtocontents{lof}{\vskip -1.2cm}
%
%\usepackage[notlot,nottoc,notlof]{}

% Max. depth of counting the sections:
%   2=subsection, 3=subsubsection
% Note: Counting below 'subsubsection'
%       is not recommended.
\setcounter{secnumdepth}{3}

% Max. depth of the Table of Contents (ToC):
%   2=subsection, 3=subsubsection
\setcounter{tocdepth}{2}
'''

# LaTeX engine to build the document.
#   'pdflatex' (default), 'xelatex',
#   'lualatex' and 'platex'.
latex_engine = 'pdflatex'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # Flex­i­ble user in­ter­face to cus­tomize the page lay­out.
    #'geometry': r'\usepackage[vmargin=2.5cm,hmargin=3cm]{geometry}',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    # Accept different input encodings.
    #'inputenc': r'\usepackage[utf8]{inputenc}',

    # Se­lect font en­cod­ings.
    #'fontenc': r'\usepackage[T1]{fontenc}',

    # Fontpackage inclusion.
#     'fontpkg': r'''
# \setmainfont{DejaVu Serif}
# \setsansfont{DejaVu Sans}
# \setmonofont{DejaVu Sans Mono}''',

    # Language package for typographical rules
    # and hyphenation patterns.
    'babel': r'\usepackage[english]{babel}',

    # Extensive support for hypertext links in
    # the doc­ument.
    #'hyperref': r'\usepackage[breaklinks=true]{hyperref}',

    # Avoid blank pages between chapters.
    'classoptions': 'openany, oneside',

    # Predefined chapter heading styles.
    #   'Bjarne' (default), 'Sonny', 'Lenny', 'Glenn',
    #   'Conny', 'Rejne' and 'Bjornstrup'.
    #'fncychap': r'\usepackage[Sonny]{fncychap}',

    # Latex figure (float) alignment
    'figure_align': 'htbp',

    # Additional stuff for the LaTeX preamble.
    'preamble': _preamble
}


# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'WBM-Library.tex', u'WBM-Library Documentation',
     u'Martin Neururer', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'wbm-library', u'WBM-Library Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'WBM-Library', u'WBM-Library Documentation',
     author, 'WBM-Library', 'The Whole-Body Model Library for YARP-based Robots.',
     'Robotics'),
]
