close all;
clear all;
clc;

addpath('./../build');
addpath('./icub_stls');
addpath('./worker_functions');
addpath('./experiment_results');

wholeBodyModel('model-initialise','icubGazeboSim');

% set the simulation parameters
set_parameters;

% initialize
initialize_forwardDyn;
%

% initialize GUI
figure_main = figure('Name', 'iCub Simulator', 'NumberTitle', 'off',...
    'Position', [50,400,600,650]);
set(figure_main, 'MenuBar', 'none', 'BackingStore', 'off');
set(figure_main, 'BackingStore', 'off');
plot_main = subplot('Position', [0.1,0.25,0.80,0.70]);

plot3(0,0,0,'.');
axis([-0.425 0.575 -0.5 0.5 0 1]); hold on;
patch([-0.425 -0.425 0.575 0.575],[-0.5 0.5 0.5 -0.5],[0 0 0 0],[0.6 0.6 0.8]);

set(gca,'Color',[0.4 0.4 0.43]);
set(gca,'XColor',[0.1 0.4 0.1]);
set(gca,'YColor',[0.4 0.1 0.1]);
set(gca,'ZColor',[0.2 0.2 0.1]);
set(gca,'xdir','reverse')
set(gca, 'drawmode', 'fast');
params.draw_init = 1;
rotate3d(gca,'on');
%
% setup GUI
gui_pushbutton_reset = uicontrol(figure_main,'Style','push','Pos',[20 20 45 24],...
    'String','Reset','CallBack',[...
    'initialize_forwardDyn;',...
    'set(gui_checkbox_visualizerLoop,''Value'',0);',...
    'if exist(''figure_contactForces'',''var'');close(figure_contactForces);',...
    'clear figure_contactForces;end;'...
    'if exist(''figure_jointTorques'',''var'');close(figure_jointTorques);',...
    'clear figure_jointTorques;end;',...
    'if exist(''figure_comTraj'',''var'');close(figure_comTraj);',...
    'clear figure_comTraj;end;',...
    'set(gui_edit_timeStep,''String'',num2str(params.sim_step));',...
    'set(gui_edit_duration,''String'',num2str(params.sim_duration));',...
    'set(params.gui.gui_edit_currentTime,''String'',''0'');',...
    'clear figure_comTraj figure_contactForces figure_jointTorques;']);

gui_pushbutton_run = uicontrol(figure_main,'Style','push','Pos',[67 20 45 24],...
    'String','Run','CallBack','simulate_forwardDyn');

gui_pushbutton_setparameters = uicontrol(figure_main,'Style','push','Pos',[207 20 155 24],...
    'String','  Set Parameters ','CallBack',['if get(gui_pushbutton_setparameters,''String'')==''  Set Parameters '';',...
    'edit set_parameters;set(gui_pushbutton_setparameters,''String'',''Update Parameters'');else;',...
    'set_parameters;set(gui_pushbutton_setparameters,''String'',''  Set Parameters '');end;']);


% gui_pushbutton_stop = uicontrol(figure_main,'Style','push','Pos',[114 20 45 24],...
%     'String','Stop','CallBack','visualize_stop = 1;');

gui_label_currentTime = uicontrol(figure_main,'Style','text','Pos',[20 90 100 17],'String','Current Time');
params.gui.gui_edit_currentTime = uicontrol(figure_main,'Style','text','Pos',[120 90 40 17],'String','0');

gui_label_duration = uicontrol(figure_main,'Style','text','Pos',[20 70 100 17],'String','Duration');
gui_edit_duration = uicontrol(figure_main,'Style','edit','Pos',[120 70 40 17],'String',num2str(params.sim_duration),'Callback',...
    ['params.sim_duration = str2num(get(gui_edit_duration,''String''));',...
     'params.tSpan   = linspace(  params.sim_start_time,  params.sim_start_time+params.sim_duration,  params.sim_duration/params.sim_step);']);

gui_label_timeStep = uicontrol(figure_main,'Style','text','Pos',[20 50 100 17],'String','Time Step');
gui_edit_timeStep = uicontrol(figure_main,'Style','edit','Pos',[120 50 40 17],'String',num2str(params.sim_step),'Callback',...
    ['params.sim_step = str2num(get(gui_edit_timeStep,''String''));',...
    'params.tSpan   = linspace(  params.sim_start_time,  params.sim_start_time+params.sim_duration,  params.sim_duration/params.sim_step);']);

gui_edit_messages = uicontrol(figure_main,'Style','edit','Max',3,'Min',1,'HorizontalAlignment','left','Pos',[182 50 200 57],'String',{'Welcome'});

gui_label_plots = uicontrol(figure_main,'Style','text','Pos',[402 110 80 17],'String','Plots:');
gui_checkbox_plot_contactForces = uicontrol(figure_main,'Style','checkbox','Pos',[402 90 80 17],...
    'String','Fc','Callback',...
    ['if get(gui_checkbox_plot_contactForces,''Value'')==1;',...
    'params.PLOT.contactForces=1;',...
    'else;',...
    'params.PLOT.contactForces=0;if exist(''figure_contactForces'',''var'');close(figure_contactForces);',...
    'clear figure_contactForces;end;',...
    'end;']);
gui_checkbox_plot_jointTorques =  uicontrol(figure_main,'Style','checkbox','Pos',[402 70 80 17],...
    'String','Torque','Callback',...
    ['if get(gui_checkbox_plot_jointTorques,''Value'')==1;',...
    'params.PLOT.jointTorques=1;',...
    'else;',...
    'params.PLOT.jointTorques=0;if exist(''figure_jointTorques'',''var'');close(figure_jointTorques);',...
    'clear figure_jointTorques;end;',...
    'end;']);

gui_checkbox_plot_comTraj =  uicontrol(figure_main,'Style','checkbox','Pos',[402 50 80 17],...
    'String','COM traj.','Callback',...
    ['if get(gui_checkbox_plot_comTraj,''Value'')==1;',...
    'params.PLOT.comTraj=1;',...
    'else;',...
    'params.PLOT.comTraj=0;if exist(''figure_comTraj'',''var'');close(figure_comTraj);',...
    'clear figure_comTraj;end;',...
    'end;']);


gui_checkbox_visualizerLoop =  uicontrol(figure_main,'Style','checkbox','Pos',[115 23 50 17],...
    'String','loop','Callback',...
    ['if get(gui_checkbox_visualizerLoop,''Value'')==1;',...
    'params.visualize_loop=1;',...
    'else;',...
    'params.visualize_loop=0;',...
    'end;']);
%




% just to test and get the initial pose
if params.draw_init==1;
    options = odeset('RelTol',1e-3,'AbsTol',1e-6);
    [t,xout] = ode15s(@(t,qv)func_forwardDyn(t, qv, params),[0 0.01 0.02],params.qvInit,options);
%     xout = xout(:,1:end-3);
    visualize_forwardDyn(xout,params);
    params.draw_init=0;
    set(params.gui.gui_edit_currentTime,'String','0');
end
%











