classdef wbmDrawProp
    properties
        joints = struct( 'marker',    '', ...
                         'marker_sz', 0, ...
                         'color',     [] );

        links  = struct( 'line_width', 0, ...
                         'color',      [] );

        com    = struct( 'marker',    '', ...
                         'marker_sz', 0, ...
                         'color',     [] );

        shape  = struct( 'line_width', 0, ...
                         'edge_color', [], ...
                         'face_color', [], ...
                         'face_alpha', 0 );
        ground_color
    end
end
